spring.application.name=chiikawa_shop

server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/chiikawadb?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true&characterEncoding=utf8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.http-only=true

#單一圖片最大10MB
spring.servlet.multipart.max-file-size=10MB
#整個Request最大10MB
spring.servlet.multipart.max-request-size=10MB
#圖片存放資料夾uploads
app.upload.dir=uploads

# MyBatis
# Entity 所在 package
mybatis.type-aliases-package=com.chiikawa.shop.entity

# MySQL snake_case 自動轉 Java camelCase
# character_name -> characterName
# image_url -> imageUrl
# created_at -> createdAt
mybatis.configuration.map-underscore-to-camel-case=true

# Mapper XML 位置
mybatis.mapper-locations=classpath:mapper/*.xml

# 自動 mapping
mybatis.configuration.auto-mapping-behavior=FULL