# ==============================================================================
# JasperReports 擴充功能註冊表 (Extension Registry)
# ==============================================================================
# 當 JasperReports 啟動時，會自動在資源目錄尋找這個特定名稱的檔案。
# 它的功用是當作「入口」，告訴系統我們有額外新增的自訂功能（例如字體）。
# 如果沒有這個檔案，系統就不會知道要去讀取 fonts.xml，中文就會印不出來。

# 1. 啟用「簡單字體擴充工廠 (Simple Font Extensions Registry Factory)」
net.sf.jasperreports.extension.registry.factory.simple.font.families=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory

# 2. 告訴系統，我們自訂的字體對應表放在 fonts/fonts.xml 這裡，請去讀取它
net.sf.jasperreports.extension.simple.font.families.fonts=fonts/fonts.xml
